"""Add harassment_flag to ChatHistory

Revision ID: 074f5e0ee09d
Revises: 4b3f00230ae8
Create Date: 2025-04-15 00:21:06.585432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074f5e0ee09d'
down_revision = '4b3f00230ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harassment_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('harassment_flag')

    # ### end Alembic commands ###
