"""initial with timestamp

Revision ID: 109d209dc716
Revises: 
Create Date: 2025-04-11 23:17:31.541513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109d209dc716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('preferred_response_type', sa.String(length=10), nullable=False),
    sa.Column('last_psychological_state', sa.String(length=20), nullable=False),
    sa.Column('previous_psychological_state', sa.String(length=20), nullable=False),
    sa.Column('stress_count', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    op.drop_table('user')
    # ### end Alembic commands ###
