"""add sensitive_flag to ChatHistory

Revision ID: 9a0067a84498
Revises: 074f5e0ee09d
Create Date: 2025-05-20 20:44:55.015558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0067a84498'
down_revision = '074f5e0ee09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('sensitive_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'sensitive_flag')
    # ### end Alembic commands ###
